### ISSUE TITLE
Slang: `Integer>>#bitOr:` and `Integer>>#|` are translated to C code differently

### ISSUE THREAD

**Issue by nrainhart** [pharo-project/pharo-vm#446]
From `Integer>>#bitOr:`:

```
| anInteger
	^self bitOr: anInteger
```

However, when translating it to C code, `Integer>>#bitOr:` is translated to `|` (bitwise or), while `Integer>>#|` is translated to `||` (logical or).

We should translate them both to bitwise or.

Note: we should check if we have the same issue with `bitAnd:` and `&`.

**Comment by privat** [comment]
On a standard PharoVMMaker generation, there are 2510 calls to `generateCASTOr:` (this counts inlining), it is not impossible that some of them should have been `generateCASTBitOr:` instead (there is 1493 of them).

Since there is no static type information on the nodes of the T AST (or the C AST) so it could be difficult to distinguish both cases.

A possibility could be to remove `|` as a valid message send in the vm code and require using either `bitOr:` or `or:`.
